### ISSUE TITLE
Unable to fetch body of page

### ISSUE THREAD

**Issue by paoloach** [JetBrains/intellij-plugin-verifier#20]
Using the version 1.219 I got the error:

java -jar verifier-cli-1.219-all.jar check-ide /opt/clion-2019.2

Verification reports directory: verification-2019-11-20 at 19.05.53
2019-11-20T19:05:53 [main] INFO  verification - Reading classes of IDE /opt/clion-2019.2
2019-11-20T19:06:20 [main] INFO  c.j.p.repository.cache.ResourceCache - Closing the PluginDetailsCache
Exception in thread "main" java.lang.RuntimeException: Unable to fetch body of page https://raw.githubusercontent.com/JetBrains/intellij-sdk-docs/master/reference_guide/api_changes/api_changes_list_2018.md
        at com.jetbrains.pluginverifier.filtering.documented.DocumentedProblemsPagesFetcher.fetchPageBody(DocumentedProblemsPagesFetcher.kt:37)
        at com.jetbrains.pluginverifier.filtering.documented.DocumentedProblemsPagesFetcher.fetchPages(DocumentedProblemsPagesFetcher.kt:24)
        at com.jetbrains.pluginverifier.options.OptionsParser.createDocumentedProblemsFilter(OptionsParser.kt:124)
        at com.jetbrains.pluginverifier.options.OptionsParser.getProblemsFilters(OptionsParser.kt:116)
        at com.jetbrains.pluginverifier.tasks.checkIde.CheckIdeParamsBuilder.build(CheckIdeParamsBuilder.kt:39)
        at com.jetbrains.pluginverifier.tasks.checkIde.CheckIdeParamsBuilder.build(CheckIdeParamsBuilder.kt:23)
        at com.jetbrains.pluginverifier.PluginVerifierMain.main(PluginVerifierMain.kt:117)
Caused by: org.jsoup.HttpStatusException: HTTP error fetching URL. Status=502, URL=https://raw.githubusercontent.com/JetBrains/intellij-sdk-docs/master/reference_guide/api_changes/api_changes_list_2018.md
        at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:590)
        at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:540)
        at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:227)
        at com.jetbrains.pluginverifier.filtering.documented.DocumentedProblemsPagesFetcher.fetchPageBody(DocumentedProblemsPagesFetcher.kt:34)
        ... 6 more

Java version is:
java version "1.8.0_202"
Java(TM) SE Runtime Environment (build 1.8.0_202-b08)
Java HotSpot(TM) 64-Bit Server VM (build 25.202-b08, mixed mode)

**Comment by serejke** [comment]
Hi, @paoloach 
Thank you for reporting the error message. It seems that [IntelliJ SDK documentation](http://www.jetbrains.org/intellij/sdk/docs/reference_guide/api_changes_list.html) site was not available for some reason. It is used to get the list of already documented incompatible IntelliJ API changes and exclude corresponding problems from verification reports.

I've altered the code to ignore and log the error and continue verification without exception.
Please use the latest version 1.221 to run the verifier locally.
