### ISSUE TITLE
Improve JDK Dir Search

### ISSUE THREAD

**Issue by opticyclic** [JetBrains/intellij-plugin-verifier#35]
The plugin takes an option to specify the runtime dir or falls back to a default.

> -runtime-dir (-r) The path to directory containing Java runtime jar. If not specified, the JDK from 'JAVA_HOME' will be chosen.

When I run from bash it works fine, however, when I run from within IDEA I get the error:

    Exception in thread "main" java.lang.IllegalArgumentException: JAVA_HOME is not specified
        at com.jetbrains.pluginverifier.options.OptionsParser.getJdkPath(OptionsParser.kt:76)
        at com.jetbrains.pluginverifier.options.OptionsParser.createIdeDescriptor(OptionsParser.kt:66)
        at com.jetbrains.pluginverifier.tasks.checkPlugin.CheckPluginParamsBuilder.build(CheckPluginParamsBuilder.kt:38)
        at com.jetbrains.pluginverifier.tasks.checkPlugin.CheckPluginParamsBuilder.build(CheckPluginParamsBuilder.kt:23)
        at com.jetbrains.pluginverifier.PluginVerifierMain.main(PluginVerifierMain.kt:124)

This is probably due to how JAVA_HOME is set in my bash profile and how IDEA is launched without inheriting all the environment variable.

I can verify this by adding an extra gradle task to output JDK info:

    task JDK {
        println "JavaHome = " + org.gradle.internal.jvm.Jvm.current().getJavaHome()
        println "java.home = " + System.getProperty('java.home')
        println "JAVA_HOME = " + System.getenv("JAVA_HOME")
    }

Which gives:

    > Configure project :
    JavaHome = /opt/jdk1.8.0_202
    java.home = /opt/jdk1.8.0_202/jre
    JAVA_HOME = null

You could probably improve the JDK search in the `OptionsParser` to account for cases like this (and others) to do a better search for the JDK.

https://github.com/JetBrains/intellij-plugin-verifier/blob/master/intellij-plugin-verifier/verifier-cli/src/main/java/com/jetbrains/pluginverifier/options/OptionsParser.kt#L69-L80

Maybe output a warning if neither of the current options are found and log what you have fallen back to.

**Comment by serejke** [comment]
Replicated this ticket in YouTrack: https://youtrack.jetbrains.com/issue/MP-3241

**Comment by serejke** [comment]
Plugin Verifier project now uses YouTrack as the bug-tracking system. See #51.
