### ISSUE TITLE
Verifier doesn't work with Java 10

### ISSUE THREAD

**Issue by hsz** [JetBrains/intellij-plugin-verifier#6]
I have tried to run verifier using Java 10, but got following error:

```
java --add-modules java.xml.bind -jar verifier-all-1.181.jar check-plugin ./build/distributions/idea-gitignore-2.6.4.181.zip ~/IDE/idea-IU-181.5087.20        
Verification reports directory: verification-2018-07-23 at 13.16.09
2018-07-23T13:16:09 [main] INFO  verification - Reading IDE /home/hsz/IDE/idea-IU-181.5087.20
2018-07-23T13:16:12 [main] INFO  verification - Parse a list of plugins to check
Task check-plugin parameters:
JDK              : /usr/lib/jvm/java-10-oracle
IDEs             : [IU-181.5087.20]
Plugins (1): [mobi.hsz.idea.gitignore:2.6.4.181]
Ignored : []
2018-07-23T13:16:12 [main] INFO  c.j.p.PluginVerifierMain - Available memory: 3,92 GB; Available CPU = 4; Concurrency level = 4
2018-07-23T13:16:12 [main] INFO  c.j.p.repository.cache.ResourceCache - Closing the JDKCache
2018-07-23T13:16:12 [main] INFO  c.j.p.repository.cache.ResourceCache - Closing the PluginDetailsCache
Exception in thread "main" java.lang.RuntimeException: Fatal: worker finished abruptly
	at com.jetbrains.pluginverifier.VerifierExecutor.waitAllWorkersInterruptibly(VerifierExecutor.kt:96)
	at com.jetbrains.pluginverifier.VerifierExecutor.verify(VerifierExecutor.kt:56)
	at com.jetbrains.pluginverifier.tasks.checkPlugin.CheckPluginTask.execute(CheckPluginTask.kt:74)
	at com.jetbrains.pluginverifier.tasks.checkPlugin.CheckPluginTask.execute(CheckPluginTask.kt:28)
	at com.jetbrains.pluginverifier.PluginVerifierMain.runVerification(PluginVerifierMain.kt:148)
	at com.jetbrains.pluginverifier.PluginVerifierMain.main(PluginVerifierMain.kt:110)
Caused by: java.lang.RuntimeException: Failed to verify mobi.hsz.idea.gitignore:2.6.4.181 against IU-181.5087.20
	at com.jetbrains.pluginverifier.PluginVerifier.call(PluginVerifier.kt:54)
	at com.jetbrains.pluginverifier.PluginVerifier.call(PluginVerifier.kt:29)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: java.lang.IllegalStateException: Unable to resolve JDK descriptor
	at com.jetbrains.pluginverifier.verifiers.resolution.DefaultClsResolverProvider.provide(DefaultClsResolverProvider.kt:72)
	at com.jetbrains.pluginverifier.verifiers.resolution.DefaultClsResolverProvider.provide(DefaultClsResolverProvider.kt:44)
	at com.jetbrains.pluginverifier.PluginVerifier.verify(PluginVerifier.kt:141)
	at com.jetbrains.pluginverifier.PluginVerifier.verify(PluginVerifier.kt:118)
	at com.jetbrains.pluginverifier.PluginVerifier.call(PluginVerifier.kt:48)
	... 7 more
Caused by: java.lang.IllegalArgumentException: JDK /usr/lib/jvm/java-10-oracle is not a valid JDK
	at com.jetbrains.plugin.structure.classes.jdk.JdkResolverCreator.createJdkResolver(JdkResolverCreator.kt:18)
	at com.jetbrains.pluginverifier.parameters.jdk.JdkDescriptorsCache$JdkClassesResourceProvider.provide(JdkDescriptorsCache.kt:37)
	at com.jetbrains.pluginverifier.parameters.jdk.JdkDescriptorsCache$JdkClassesResourceProvider.provide(JdkDescriptorsCache.kt:33)
	at com.jetbrains.pluginverifier.repository.resources.ResourceRepositoryImpl.fetchAndAddResource(ResourceRepositoryImpl.kt:205)
	at com.jetbrains.pluginverifier.repository.resources.ResourceRepositoryImpl.access$fetchAndAddResource(ResourceRepositoryImpl.kt:20)
	at com.jetbrains.pluginverifier.repository.resources.ResourceRepositoryImpl$getOrWait$$inlined$synchronized$lambda$1.call(ResourceRepositoryImpl.kt:178)
	at com.jetbrains.pluginverifier.repository.resources.ResourceRepositoryImpl$getOrWait$$inlined$synchronized$lambda$1.call(ResourceRepositoryImpl.kt:20)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.jetbrains.pluginverifier.repository.resources.ResourceRepositoryImpl.getOrWait(ResourceRepositoryImpl.kt:188)
	at com.jetbrains.pluginverifier.repository.resources.ResourceRepositoryImpl.get(ResourceRepositoryImpl.kt:263)
	at com.jetbrains.pluginverifier.repository.cache.ResourceCache.getResourceCacheEntry(ResourceCache.kt:144)
	at com.jetbrains.pluginverifier.parameters.jdk.JdkDescriptorsCache.getJdkResolver(JdkDescriptorsCache.kt:29)
	at com.jetbrains.pluginverifier.verifiers.resolution.DefaultClsResolverProvider.provide(DefaultClsResolverProvider.kt:58)
	... 11 more
```

The problem is because in Java 10 there is no `rt.jar` file present in `$JAVA_HOME/lib/` directory.

Ref: https://docs.oracle.com/javase/10/migrate/toc.htm#JSMIG-GUID-A78CC891-701D-4549-AA4E-B8DD90228B4B (_Removed rt.jar and tools.jar_ section).

**Comment by serejke** [comment]
Currently, IDEA cannot be run with Java 10. Neither should your plugin.
This is why there is no sense to verify the plugin against Java 10 yet.
Please, use JRE 8 instead

**Comment by serejke** [comment]
Now IDEA can be run (and by default is) with JDK 11, so the Plugin Verifier also supports JDKs 9 — 11
